version: '3.3'

services:
  expo:
    build: .
    volumes:
      - .:/app
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
      - "19006:19006"
      - "8081:8081"
    command: bash
    stdin_open: true
    tty: true
